"""added message table

Revision ID: 931a130eabe9
Revises: 
Create Date: 2024-12-15 00:15:37.974582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931a130eabe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_conversation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_conversation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=50), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['uploaded_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
